const userData = [
  {
    fullName: "Sarah Johnson",
    email: "sarah.johnson@email.com",
    billingDate: "2024-03-15",
    plan: "premium",
    totalUsers: 32,
    amount: 28000,
  },
  {
    fullName: "Michael Chen",
    email: "michael.chen@company.net",
    billingDate: "2024-04-01",
    plan: "basic",
    totalUsers: 8,
    amount: 5600,
  },
  {
    fullName: "Emma Thompson",
    email: "emma.t@business.com",
    billingDate: "2024-03-28",
    plan: "team",
    totalUsers: 45,
    amount: 42000,
  },
  {
    fullName: "David Wilson",
    email: "david.wilson@corp.org",
    billingDate: "2024-04-10",
    plan: "premium",
    totalUsers: 25,
    amount: 22500,
  },
  {
    fullName: "Lisa Anderson",
    email: "lisa.anderson@team.net",
    billingDate: "2024-03-20",
    plan: "basic",
    totalUsers: 12,
    amount: 7800,
  },
  {
    fullName: "Robert Taylor",
    email: "robert.t@enterprise.com",
    billingDate: "2024-04-05",
    plan: "team",
    totalUsers: 50,
    amount: 47500,
  },
  {
    fullName: "Jennifer Brown",
    email: "jen.brown@startup.io",
    billingDate: "2024-03-25",
    plan: "premium",
    totalUsers: 18,
    amount: 16200,
  },
  {
    fullName: "Thomas Garcia",
    email: "t.garcia@agency.com",
    billingDate: "2024-04-15",
    plan: "basic",
    totalUsers: 5,
    amount: 5000,
  },
  {
    fullName: "Rachel Martinez",
    email: "rachel.m@techgroup.com",
    billingDate: "2024-03-18",
    plan: "team",
    totalUsers: 38,
    amount: 35000,
  },
  {
    fullName: "Kevin Wright",
    email: "kevin.wright@digital.net",
    billingDate: "2024-04-08",
    plan: "premium",
    totalUsers: 28,
    amount: 25200,
  },
  {
    fullName: "Amanda Cooper",
    email: "amanda.c@startup.com",
    billingDate: "2024-03-22",
    plan: "basic",
    totalUsers: 15,
    amount: 9000,
  },
  {
    fullName: "Brian Murphy",
    email: "brian.murphy@corp.com",
    billingDate: "2024-04-12",
    plan: "team",
    totalUsers: 42,
    amount: 39900,
  },
  {
    fullName: "Jessica Lee",
    email: "jessica.lee@tech.io",
    billingDate: "2024-03-30",
    plan: "premium",
    totalUsers: 22,
    amount: 19800,
  },
  {
    fullName: "Mark Peterson",
    email: "mark.p@agency.net",
    billingDate: "2024-04-03",
    plan: "basic",
    totalUsers: 10,
    amount: 6500,
  },
  {
    fullName: "Laura Santos",
    email: "laura.santos@group.com",
    billingDate: "2024-03-27",
    plan: "team",
    totalUsers: 35,
    amount: 33250,
  },
];


export default userData;